/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mytokenSol from "./mytoken.sol";
export type { mytokenSol };
export type { SimpleSwap } from "./SimpleSwap";
