/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mytokenSol from "./mytoken.sol";
export { SimpleSwap__factory } from "./SimpleSwap__factory";
